### ISSUE TITLE
Can't find the route, timeout

### ISSUE THREAD

**Issue by Vadorequest** [mikestaub/serverless-express#13]
I don't know what I did wrong, but the most basic example doesn't work, it just hangs and timeout after 30 sec when I hit `http://localhost:7000/api/dialogflow`:

serverless.yml
```yml
  dialogflow-debug:
    handler: src/api/dialogflow/index.handler
    events:
    - http:
        path: api/dialogflow
        method: get
        cors: true
```

src/express-app.js
```js
import express from 'serverless-express/express';

const app = express();

app.get('*', () => {
  console.log('HIT')
});

export default app;

```

src/api/dialogflow/index.js
```js
import expressHandler from 'serverless-express/handler';
import app from '../../express-app';

export const handler = ()=>{
  return expressHandler(app)
};
```

Any idea what's the issue?
Maybe it's related to the localhost environment? I use serverless-offline:

```yml
plugins:
- serverless-webpack # Must be first, see https://github.com/99xt/serverless-dynamodb-local#using-with-serverless-offline-and-serverless-webpack-plugin
- serverless-sentry # https://github.com/arabold/serverless-sentry-plugin
- '@jimdo/serverless-dotenv' # See https://github.com/Jimdo/serverless-dotenv
- serverless-offline # See https://github.com/dherault/serverless-offline
- serverless-express # See https://github.com/mikestaub/serverless-express
- serverless-domain-manager # See https://github.com/amplify-education/serverless-domain-manager
```
