### ISSUE TITLE
Error when using external config files

### ISSUE THREAD

**Issue by mtford90** [mikestaub/serverless-express#16]
I have the following line in my config:

```yaml
provider:
  name: aws
  # ...
  environment: ${file(../../serverless/consumer_env.yml)}
```

When I run `serverless deploy` I see the following:

```
 Cannot create property 'SERVERLESS_EXPRESS_PLATFORM' on string '${file(../../serverless/consumer_env.yml)}'
```

**Comment by iliasbhal** [comment]
Hi, @mtford90,
I'm looking at it right now

**Comment by iliasbhal** [comment]
@mtford90 
- I did the exact same configuration, and it didn't throw any error
- the function is deployed with all environment variables.

Can you share the version of your local serverless-cli and serverless-express ?

**Comment by mtford90** [comment]
Hey @iliasbhal - appreciate the speed! 

- `serverless-express`: 2.0.11
- `serverless-cli`: 1.38.0

Here's my full yml (with some obfuscation):

```
service:
  name: xxx

plugins:
  - serverless-webpack
  - serverless-express

custom:
  stages:
    - dev
    - prod
  ssm: ${file(../../serverless/ssm.yml)}
  # https://github.com/serverless-heaven/serverless-webpack/issues/342#issuecomment-383248835
  webpack:
    packExternalModulesMaxBuffer: 1000000
    includeModules: true
    packagerOptions:
      scripts:
        - npm rebuild grpc --target=8.1.0 --target_arch=x64 --target_platform=linux --target_libc=glibc
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:HeadBucket
        - s3:GetObject
        - s3:ListBucket
      Resource: "xxx"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:GetObjectAcl
        - s3:PutObjectTagging
        - s3:ListBucket
        - s3:PutObjectVersionTagging
        - s3:PutObjectVersionAcl
        - s3:GetObjectTagging
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "xxx"

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs8.10
  timeout: 32
  stage: ${opt:stage,'dev'}
  environment: ${file(../../serverless/consumer_env.yml)}
  vpc:
    securityGroupIds:
      - xxx
    subnetIds:
      - xxx
      - xxx
      - xxx

functions:
  express:
    handler: src/lambda.handler
    memorySize: 2048
    environment:
      SENTRY_DSN: xxx
    events:
      - http:
          path: /{proxy+}
          method: ANY

package:
  #  individually: true
  exclude:
    - ./node_modules/ava/**
    - ./**/*.test.ts

```

**Comment by iliasbhal** [comment]
@mtford90 I'll take time to fix this bug this weekend.
In the meantime, you can do this quick hotfix:

Assign the variables to the function instead of the provider. 
I tested it and it's working great. but it's a hotfix, I'll push something this weekend ;)

```yaml
functions:
  express:
    handler: src/lambda.handler
    memorySize: 2048
    environment:  ${file(../../serverless/consumer_env.yml)}
```
