### ISSUE TITLE
Error with README instructions

### ISSUE THREAD

**Issue by ValentinPcl** [mikestaub/serverless-express#23]
Hello !
First of all thank you for your amazing work.

I am just pointing out a minor mistake in the readme.md that could lead to errors.
In the "Usage" section of the readme, "path" and "method" are inverted:
```

functions:
  app: 
    handler: handler.handler  #assuming your handler file is handler.js
    events: 
      - http:
          path: GET
          method: /users

```
Instead of:
```
functions:
  app: 
    handler: handler.handler  #assuming your handler file is handler.js
    events: 
      - http:
          path: /users
          method: GET
```

Wishing you an amazing day
