### ISSUE TITLE
No APIs are hitting its Showing `404 Error`

### ISSUE THREAD

**Issue by Vikas252** [mikestaub/serverless-express#50]
I'm currently using simple API's system with serverless and this plugin cant able to hit the API's it shows a 404 error page.

![2022-10-31 (1)](https://user-images.githubusercontent.com/73119144/198983869-1cd619e5-33e5-467b-9aaa-d917b0049290.png)

hello.js:
```
"use strict"
const express = require('serverless-express/express')
const compression = require("compression")
const cors = require("cors")
const bodyParser = require("body-parser")

const app = express()
const router = express.Router()

router.use(compression())
router.use(cors())
router.use(bodyParser.json())
router.use(bodyParser.urlencoded({ extended: true }))
  
router.get("/api/serverless", (req, res) => {
  res.json("hi")
})

router.get("/api/sls", (req, res) => {
  res.json("bye")
})
  
app.use("/", router)

module.exports = app
```
handler.js
```
const handler = require('serverless-express/handler')
const app = require('./hello')

module.exports = handler(app)
```

serverless.yml
```
service: serverless
provider:
  name: azure
  region: West US 2
  runtime: nodejs14
  environment:
    VARIABLE_FOO: foo
plugins:
  - serverless-azure-functions
  - serverless-express
package:
  patterns:
    - "!local.settings.json"
    - "!.vscode/**"
functions:
  handler:
    handler: src/handlers/handler.handler
    events: 
      - http:
          method: ANY   
          path: /{proxy+}
```

Azure Functions Core Tools
Core Tools Version:       3.0.4837 Commit hash: N/A  (64-bit)
Function Runtime Version: 3.14.1.0
Node Version: 14.20.1
Running on dev containers (Docker)
